CC = mpicc
AR = ar r

CFLAGS = -Wall -Wextra -O3 -g -rdynamic
INCLUDE = -I/usr/include/glib-2.0

SRCS = $(wildcard *.c)
OBJS = $(patsubst %.c, ../build/%.o, $(SRCS))

TARGET = ../build/libibm3d.a

.PHONY: clean mkbuild

all: mkbuild $(TARGET)

$(TARGET): $(OBJS)
	$(AR) $@ $(OBJS)

$(OBJS): ../build/%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS) $(INCLUDE)

clean:
	rm -rf ../build

mkbuild: ../build

../build:
	mkdir -p ../build
